In [ ]:
import requests
import pandas as pd
import numpy as np 
import json

# 데이터수집

# 년도별 총 헌혈자수

In [ ]:
year = pd.read_csv('./데이터원본/year(2005~2024).csv')
year.head()
year.info()
year.describe()

year.to_csv("year_clean.csv", index=False, encoding="utf-8-sig")

In [ ]:
year = pd.read_csv('./전처리/year_clean.csv')
year.columns
# 컬럼정리
year = year[['시점','헌혈가능인구 (16~69세) (명)','헌혈자 실인원 (명)','헌혈자 1인당 평균 헌혈실적 (건)','총 헌혈실적 (건)']]

# 컬럼이름변경
year = year.rename(columns={
    '헌혈가능인구 (16~69세) (명)': '헌혈가능인구',
    '헌혈자 실인원 (명)': '헌혈자수',
    '헌혈자 1인당 평균 헌혈실적 (건)': '1인당평균헌혈',
    '총 헌혈실적 (건)': '총헌혈건수',
    '시점':'년도'
})

year.info()
year.tail()

#파일저장
year.to_csv("year2.csv", index=False, encoding="utf-8-sig")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   년도       20 non-null     int64
 1   헌혈가능인구   20 non-null     int64
 2   헌혈자수     20 non-null     int64
 3   1인당평균헌혈  20 non-null     float64
 4   총헌혈건수    20 non-null     int64
dtypes: float64(1), int64(4)
memory usage: 932.0 bytes

# 월별 헌혈건수

In [ ]:
url = 'https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=NDM2YzQ2NTdiNTBkM2QyNDg4ZjYyNDYzNzg4OTQwY2U=&itmId=T001+T002+T003+T004+T005+T006+T007+T008+&objL1=&objL2=&objL3=&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=Y&startPrdDe=2005&endPrdDe=2024&orgId=445&tblId=DT_445001_007'
response = requests.get(url)

In [75]:
# api 함수생성

import requests
import pandas as pd

def get_data(url):
    response = requests.get(url)
    data = response.json()
    
    df = pd.DataFrame(data)
    return df
month = get_data(url)
# month.head()
month.head()

#원본저장
month.to_csv("month(2005~2024).csv", index=False, encoding="utf-8-sig")

In [ ]:
# 한글변경
month= month.rename(columns={
    'C1_OBJ_NM': '성별',
    'C2_NM': '월',
    'DT': '헌혈건수',
    'PRD_DE': '연도',
    'C1_NM': '구분',
    'TBL_NM': '테이블명',
    'UNIT_NM':'단위'
})

month=month[['헌혈건수','월','단위','연도']]

In [ ]:
# 데이터확인
month.head()

# # 월컬럼 합계 행 삭제
month=month[month['월'] != '합계']
month['월']

# 단위 컬럼 %행 삭제
month = month[month['단위'] != '%']

# # 단위 컬럼삭제
month = month.drop(columns=['단위'])

# # 데이터 타입확인
# month.info()

# 결측치 - -> 0
month['헌혈건수'] = month['헌혈건수'].fillna(0)

# 전체 컬럼 공백 제거 
month.columns = month.columns.str.strip()

# 타입변환
month['헌혈건수'] = pd.to_numeric(month['헌혈건수'], errors='coerce')
month['연도'] = pd.to_numeric(month['연도'], errors='coerce')
month['월'] = (
    month['월']
    .astype(str)
    .str.replace('월', '')
    .pipe(pd.to_numeric, errors='coerce')
)

# 년도,월 컬럼 정렬
month = month.sort_values(['연도', '월']).reset_index(drop=True)
month.head(5)

# month['헌혈건수']

0        169087.0
1        165863.0
2         15577.0
3         10614.0
4         13714.0
5         14671.0
6         16351.0
7         13780.0
8          9870.0
9          5617.0
10        11535.0
11         6816.0
12         4899.0
13        13057.0
14         7654.0
15        12237.0
16         7125.0
17         2346.0
18         3224.0
19       141112.0
20       138540.0
21        12876.0
22         9645.0
23        11317.0
24        12148.0
25        12258.0
26        11495.0
27         7304.0
28         4618.0
29         9798.0
30         6459.0
31         4200.0
32        11922.0
33         6639.0
34         9603.0
35         6526.0
36         1732.0
37         2572.0
38        27975.0
39        27323.0
40         2701.0
41          969.0
42         2397.0
43         2523.0
44         4093.0
45         2285.0
46         2566.0
47          999.0
48         1737.0
49          357.0
50          699.0
51         1135.0
52         1015.0
53         2634.0
54          599.0
55          614.0
56          652.0
57       154943.0
58       151513.0
59        14954.0
60         9854.0
61        12025.0
62        12968.0
63        13478.0
64        13673.0
65         9465.0
66         4277.0
67        10495.0
68         6023.0
69         4664.0
70        11029.0
71         7363.0
72        11963.0
73         6955.0
74         2327.0
75         3430.0
76       127904.0
77       125064.0
78        12283.0
79         8703.0
80         9839.0
81        10516.0
82         9563.0
83        11130.0
84         6667.0
85         3384.0
86         9174.0
87         5690.0
88         4067.0
89        10119.0
90         6282.0
91         9470.0
92         6405.0
93         1772.0
94         2840.0
95        27039.0
96        26449.0
97         2671.0
98         1151.0
99         2186.0
100        2452.0
101        3915.0
102        2543.0
103        2798.0
104         893.0
105        1321.0
106         333.0
107         597.0
108         910.0
109        1081.0
110        2493.0
111         550.0
112         555.0
113         590.0
114      194115.0
115      189109.0
116       18205.0
117       11245.0
118       15110.0
119       18069.0
120       17792.0
121       16946.0
122       10984.0
123        6244.0
124       10956.0
125        7189.0
126        6841.0
127       15720.0
128        9793.0
129       13956.0
130        7568.0
131        2491.0
132        5006.0
133      158385.0
134      154151.0
135       15558.0
136        9824.0
137       12326.0
138       15210.0
139       13703.0
140       12810.0
141        8222.0
142        5186.0
143        9173.0
144        6466.0
145        5461.0
146       13823.0
147        7257.0
148       10395.0
149        6601.0
150        2136.0
151        4234.0
152       35730.0
153       34958.0
154        2647.0
155        1421.0
156        2784.0
157        2859.0
158        4089.0
159        4136.0
160        2762.0
161        1058.0
162        1783.0
163         723.0
164        1380.0
165        1897.0
166        2536.0
167        3561.0
168         967.0
169         355.0
170         772.0
171      194710.0
172      190260.0
173       17090.0
174       10092.0
175       15030.0
176       16005.0
177       18674.0
178       16874.0
179       12008.0
180        6375.0
181       12221.0
182        7443.0
183        6746.0
184       14467.0
185       10973.0
186       16031.0
187        7801.0
188        2430.0
189        4450.0
190      156055.0
191      152362.0
192       12997.0
193        8690.0
194       12562.0
195       13426.0
196       14938.0
197       12731.0
198        7548.0
199        5233.0
200       10478.0
201        6519.0
202        5256.0
203       12666.0
204        8411.0
205       12335.0
206        6680.0
207        1892.0
208        3693.0
209       38655.0
210       37898.0
211        4093.0
212        1402.0
213        2468.0
214        2579.0
215        3736.0
216        4143.0
217        4460.0
218        1142.0
219        1743.0
220         924.0
221        1490.0
222        1801.0
223        2562.0
224        3696.0
225        1121.0
226         538.0
227         757.0
228      211267.0
229      206129.0
230       18483.0
231       11771.0
232       17284.0
233       15817.0
234       22064.0
235       17695.0
236       11019.0
237        7096.0
238       12393.0
239        7107.0
240        7806.0
241       15795.0
242       11485.0
243       17134.0
244       10374.0
245        2806.0
246        5138.0
247      165864.0
248      161559.0
249       14086.0
250        9642.0
251       14679.0
252       12347.0
253       16904.0
254       12818.0
255        6799.0
256        5852.0
257       10254.0
258        6353.0
259        5903.0
260       13561.0
261        8391.0
262       12354.0
263        9334.0
264        2282.0
265        4305.0
266       45403.0
267       44570.0
268        4397.0
269        2129.0
270        2605.0
271        3470.0
272        5160.0
273        4877.0
274        4220.0
275        1244.0
276        2139.0
277         754.0
278        1903.0
279        2234.0
280        3094.0
281        4780.0
282        1040.0
283         524.0
284         833.0
285      191849.0
286      187169.0
287       17306.0
288       11442.0
289       16804.0
290       15672.0
291       18583.0
292       15198.0
293       11114.0
294        6694.0
295       10782.0
296        6442.0
297        6789.0
298       13924.0
299       10428.0
300       14720.0
301        8483.0
302        2788.0
303        4680.0
304      154675.0
305      150670.0
306       13739.0
307        9394.0
308       13688.0
309       12983.0
310       14641.0
311       10954.0
312        8092.0
313        5102.0
314        9088.0
315        5871.0
316        5300.0
317       12348.0
318        8149.0
319       11111.0
320        7765.0
321        2445.0
322        4005.0
323       37174.0
324       36499.0
325        3567.0
326        2048.0
327        3116.0
328        2689.0
329        3942.0
330        4244.0
331        3022.0
332        1592.0
333        1694.0
334         571.0
335        1489.0
336        1576.0
337        2279.0
338        3609.0
339         718.0
340         343.0
341         675.0
342      188587.0
343      184885.0
344       17776.0
345       11107.0
346       13057.0
347       16423.0
348       17662.0
349       16526.0
350       10842.0
351        7176.0
352       10673.0
353        6927.0
354        6823.0
355       14798.0
356       10751.0
357       14503.0
358        6915.0
359        2926.0
360        3702.0
361      153434.0
362      150419.0
363       14313.0
364        9438.0
365       10572.0
366       13583.0
367       13862.0
368       12836.0
369        7509.0
370        5641.0
371        9089.0
372        6396.0
373        5314.0
374       13230.0
375        9267.0
376       11188.0
377        5952.0
378        2229.0
379        3015.0
380       35153.0
381       34466.0
382        3463.0
383        1669.0
384        2485.0
385        2840.0
386        3800.0
387        3690.0
388        3333.0
389        1535.0
390        1584.0
391         531.0
392        1509.0
393        1568.0
394        1484.0
395        3315.0
396         963.0
397         697.0
398         687.0
399      200611.0
400      197531.0
401       19727.0
402       11787.0
403       16828.0
404       18151.0
405       17688.0
406       16914.0
407       11793.0
408        7525.0
409       12502.0
410        7534.0
411        6833.0
412       14386.0
413       10132.0
414       15340.0
415        7549.0
416        2842.0
417        3080.0
418      165407.0
419      162983.0
420       16511.0
421       10140.0
422       13849.0
423       15424.0
424       13424.0
425       13496.0
426        8622.0
427        5626.0
428       10564.0
429        6930.0
430        5782.0
431       12917.0
432        8543.0
433       12430.0
434        6500.0
435        2225.0
436        2424.0
437       35204.0
438       34548.0
439        3216.0
440        1647.0
441        2979.0
442        2727.0
443        4264.0
444        3418.0
445        3171.0
446        1899.0
447        1938.0
448         604.0
449        1051.0
450        1469.0
451        1589.0
452        2910.0
453        1049.0
454         617.0
455         656.0
456      190581.0
457      186179.0
458       16137.0
459       11320.0
460       13078.0
461       15791.0
462       18117.0
463       16896.0
464       10752.0
465        6813.0
466       11783.0
467        6940.0
468        6232.0
469       13936.0
470       11533.0
471       14196.0
472        9903.0
473        2752.0
474        4402.0
475      154352.0
476      150552.0
477       12775.0
478        9478.0
479       10866.0
480       13170.0
481       14647.0
482       11977.0
483        8089.0
484        5496.0
485       10135.0
486        6196.0
487        5086.0
488       12124.0
489        9046.0
490       10575.0
491        8764.0
492        2128.0
493        3800.0
494       36229.0
495       35627.0
496        3362.0
497        1842.0
498        2212.0
499        2621.0
500        3470.0
501        4919.0
502        2663.0
503        1317.0
504        1648.0
505         744.0
506        1146.0
507        1812.0
508        2487.0
509        3621.0
510        1139.0
511         624.0
512         602.0
513      175734.0
514      171053.0
515       15673.0
516       10383.0
517       15220.0
518       13751.0
519       16978.0
520       15190.0
521        8245.0
522        7464.0
523       10133.0
524        5896.0
525        6122.0
526       10926.0
527       10675.0
528       14620.0
529        6917.0
530        2860.0
531        4681.0
532      139089.0
533      135301.0
534       12097.0
535        8710.0
536       12956.0
537       10746.0
538       13766.0
539       11564.0
540        5466.0
541        5603.0
542        8680.0
543        5178.0
544        4223.0
545        8747.0
546        7904.0
547       11229.0
548        6032.0
549        2400.0
550        3788.0
551       36645.0
552       35752.0
553        3576.0
554        1673.0
555        2264.0
556        3005.0
557        3212.0
558        3626.0
559        2779.0
560        1861.0
561        1453.0
562         718.0
563        1899.0
564        2179.0
565        2771.0
566        3391.0
567         885.0
568         460.0
569         893.0
570      205282.0
571      199378.0
572       19032.0
573       11004.0
574       17272.0
575       19908.0
576       17860.0
577       17239.0
578       12985.0
579        6670.0
580       12135.0
581        7402.0
582        7071.0
583       11666.0
584       10075.0
585       15838.0
586       10545.0
587        2676.0
588        5904.0
589      159954.0
590      155060.0
591       15171.0
592        8743.0
593       14776.0
594       14982.0
595       13162.0
596       12352.0
597        9034.0
598        5044.0
599       10184.0
600        6615.0
601        5441.0
602        9337.0
603        7522.0
604       11566.0
605        9015.0
606        2116.0
607        4894.0
608       45328.0
609       44318.0
610        3861.0
611        2261.0
612        2496.0
613        4926.0
614        4698.0
615        4887.0
616        3951.0
617        1626.0
618        1951.0
619         787.0
620        1630.0
621        2329.0
622        2553.0
623        4272.0
624        1530.0
625         560.0
626        1010.0
627      197570.0
628      194567.0
629       20646.0
630       12960.0
631       15443.0
632       18313.0
633       17977.0
634       17221.0
635       10197.0
636        6799.0
637       12754.0
638        7403.0
639        6525.0
640       11608.0
641       10051.0
642       13812.0
643       10428.0
644        2430.0
645        3003.0
646      155382.0
647      152864.0
648       17418.0
649       11450.0
650       12544.0
651       14149.0
652       12266.0
653       12540.0
654        7163.0
655        5043.0
656       10799.0
657        6835.0
658        4719.0
659        9836.0
660        8046.0
661        9794.0
662        8651.0
663        1611.0
664        2518.0
665       42188.0
666       41703.0
667        3228.0
668        1510.0
669        2899.0
670        4164.0
671        5711.0
672        4681.0
673        3034.0
674        1756.0
675        1955.0
676         568.0
677        1806.0
678        1772.0
679        2005.0
680        4018.0
681        1777.0
682         819.0
683         485.0
684      176015.0
685      173132.0
686       17563.0
687        9334.0
688       14679.0
689       16292.0
690       16581.0
691       13385.0
692        9982.0
693        8311.0
694       11090.0
695        5810.0
696        5505.0
697       11187.0
698        8668.0
699       16052.0
700        6829.0
701        1864.0
702        2883.0
703      142314.0
704      140051.0
705       14436.0
706        7800.0
707       11942.0
708       13258.0
709       12481.0
710       10970.0
711        7915.0
712        6343.0
713        8810.0
714        5299.0
715        4457.0
716        9793.0
717        7308.0
718       11793.0
719        5985.0
720        1461.0
721        2263.0
722       33701.0
723       33081.0
724        3127.0
725        1534.0
726        2737.0
727        3034.0
728        4100.0
729        2415.0
730        2067.0
731        1968.0
732        2280.0
733         511.0
734        1048.0
735        1394.0
736        1360.0
737        4259.0
738         844.0
739         403.0
740         620.0
741      188463.0
742      184860.0
743       18748.0
744       11299.0
745       14070.0
746       17303.0
747       17608.0
748       14838.0
749       10249.0
750        7562.0
751       12407.0
752        7711.0
753        6375.0
754       10374.0
755        7494.0
756       18199.0
757        8453.0
758        2170.0
759        3603.0
760      148704.0
761      145624.0
762       15011.0
763        9182.0
764       11041.0
765       13936.0
766       12099.0
767       11570.0
768        7614.0
769        5626.0
770       10064.0
771        7137.0
772        5392.0
773        8656.0
774        5966.0
775       13206.0
776        7357.0
777        1767.0
778        3080.0
779       39759.0
780       39236.0
781        3737.0
782        2117.0
783        3029.0
784        3367.0
785        5509.0
786        3268.0
787        2635.0
788        1936.0
789        2343.0
790         574.0
791         983.0
792        1718.0
793        1528.0
794        4993.0
795        1096.0
796         403.0
797         523.0
798      207363.0
799      202401.0
800       20431.0
801       12681.0
802       18006.0
803       14994.0
804       19322.0
805       18376.0
806       10521.0
807        7028.0
808       12674.0
809        8223.0
810        7057.0
811       13583.0
812       11062.0
813       15478.0
814       10283.0
815        2682.0
816        4962.0
817      164826.0
818      160293.0
819       16657.0
820       10747.0
821       14432.0
822       11410.0
823       14804.0
824       13624.0
825        8379.0
826        5888.0
827       10837.0
828        7383.0
829        5562.0
830       10473.0
831        7722.0
832       11120.0
833        8968.0
834        2287.0
835        4533.0
836       42537.0
837       42108.0
838        3774.0
839        1934.0
840        3574.0
841        3584.0
842        4518.0
843        4752.0
844        2142.0
845        1140.0
846        1837.0
847         840.0
848        1495.0
849        3110.0
850        3340.0
851        4358.0
852        1315.0
853         395.0
854         429.0
855      197756.0
856      193844.0
857       19001.0
858       11852.0
859       16555.0
860       17238.0
861       18257.0
862       17497.0
863        9363.0
864        6542.0
865       12566.0
866        6857.0
867        6633.0
868       12463.0
869       11212.0
870       16121.0
871        9437.0
872        2250.0
873        3912.0
874      153485.0
875      149977.0
876       14329.0
877        9879.0
878       13127.0
879       12653.0
880       14314.0
881       13479.0
882        6065.0
883        5370.0
884       10212.0
885        6044.0
886        5025.0
887        9687.0
888        7800.0
889       12094.0
890        8147.0
891        1752.0
892        3508.0
893       44271.0
894       43867.0
895        4672.0
896        1973.0
897        3428.0
898        4585.0
899        3943.0
900        4018.0
901        3298.0
902        1172.0
903        2354.0
904         813.0
905        1608.0
906        2776.0
907        3412.0
908        4027.0
909        1290.0
910         498.0
911         404.0
912      217526.0
913      212615.0
914       20793.0
915       12504.0
916       17771.0
917       17707.0
918       20927.0
919       18874.0
920        9691.0
921        7389.0
922       13286.0
923        6653.0
924        7783.0
925       13892.0
926       12877.0
927       20905.0
928        9032.0
929        2531.0
930        4911.0
931      165902.0
932      161391.0
933       16145.0
934       10181.0
935       14076.0
936       13475.0
937       15896.0
938       13640.0
939        6527.0
940        5833.0
941       10544.0
942        5727.0
943        5962.0
944       10525.0
945        8774.0
946       14592.0
947        7406.0
948        2088.0
949        4511.0
950       51624.0
951       51224.0
952        4648.0
953        2323.0
954        3695.0
955        4232.0
956        5031.0
957        5234.0
958        3164.0
959        1556.0
960        2742.0
961         926.0
962        1821.0
963        3367.0
964        4103.0
965        6313.0
966        1626.0
967         443.0
968         400.0
969      197937.0
970      194799.0
971       19092.0
972       12101.0
973       15256.0
974       17790.0
975       16708.0
976       17038.0
977       10897.0
978        7681.0
979       13077.0
980        6677.0
981        6588.0
982       12664.0
983       10733.0
984       16275.0
985        9221.0
986        3001.0
987        3138.0
988      153498.0
989      150726.0
990       14383.0
991        9538.0
992       12093.0
993       13631.0
994       12955.0
995       12063.0
996        7876.0
997        6343.0
998       10872.0
999        5783.0
1000       4887.0
1001      10110.0
1002       8073.0
1003      11922.0
1004       7692.0
1005       2505.0
1006       2772.0
1007      44439.0
1008      44073.0
1009       4709.0
1010       2563.0
1011       3163.0
1012       4159.0
1013       3753.0
1014       4975.0
1015       3021.0
1016       1338.0
1017       2205.0
1018        894.0
1019       1701.0
1020       2554.0
1021       2660.0
1022       4353.0
1023       1529.0
1024        496.0
1025        366.0
1026     187759.0
1027     184340.0
1028      18884.0
1029      10377.0
1030      14625.0
1031      17977.0
1032      18173.0
1033      15553.0
1034       9137.0
1035       6509.0
1036      11714.0
1037       5495.0
1038       6900.0
1039      12405.0
1040       9466.0
1041      15726.0
1042       8556.0
1043       2843.0
1044       3419.0
1045     148515.0
1046     145725.0
1047      14840.0
1048       8978.0
1049      11428.0
1050      13896.0
1051      14007.0
1052      11696.0
1053       6447.0
1054       5176.0
1055       9441.0
1056       4882.0
1057       5452.0
1058      10454.0
1059       7754.0
1060      11672.0
1061       7313.0
1062       2289.0
1063       2790.0
1064      39244.0
1065      38615.0
1066       4044.0
1067       1399.0
1068       3197.0
1069       4081.0
1070       4166.0
1071       3857.0
1072       2690.0
1073       1333.0
1074       2273.0
1075        613.0
1076       1448.0
1077       1951.0
1078       1712.0
1079       4054.0
1080       1243.0
1081        554.0
1082        629.0
1083     195301.0
1084     191245.0
1085      18813.0
1086      11297.0
1087      16043.0
1088      18172.0
1089      17007.0
1090      14871.0
1091      10014.0
1092       7649.0
1093      11395.0
1094       6923.0
1095       6506.0
1096      11731.0
1097      10015.0
1098      19737.0
1099       7540.0
1100       3532.0
1101       4056.0
1102     156840.0
1103     153663.0
1104      15376.0
1105       9188.0
1106      13255.0
1107      14496.0
1108      13178.0
1109      11575.0
1110       7828.0

In [ ]:
# 결측치확인
print(month['월'].unique())
print(month['월'].isna().sum())

# month[['연도', '월']].head(20)

# 데이터 연도,월로 groupby
month = month.groupby(['연도', '월'])['헌혈건수'].sum().reset_index()
month.head()

month['연도'].unique()
#[2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
#        2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024])

[ 1  2  3  4  5  6  7  8  9 10 11 12]
0

array([2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024])

In [ ]:
# 파일저장
month.to_csv("month_clean.csv", index=False, encoding="utf-8-sig")

#전처리파일저장
month = pd.read_csv('./전처리/month_clean.csv')
month.head()
month.info()
month.to_csv('전처리2/month2.csv', index=False, encoding='utf-8-sig')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   연도      240 non-null    int64
 1   월       240 non-null    int64
 2   헌혈건수    240 non-null    float64
dtypes: float64(1), int64(2)
memory usage: 5.8 KB

# 총헌혈수 (지역별)

In [ ]:
url ='https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=NDM2YzQ2NTdiNTBkM2QyNDg4ZjYyNDYzNzg4OTQwY2U=&itmId=T001+T002+T003+&objL1=ALL&objL2=&objL3=&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=Y&startPrdDe=2005&endPrdDe=2024&orgId=445&tblId=DT_445001_013'

import requests
import pandas as pd

def get_data(url):
    response = requests.get(url)
    data = response.json()
    
    df = pd.DataFrame(data)
    return df
region = get_data(url)


region.head() # C1_NM 합계,지역이름

#원본저장
# region.to_csv("region(2025~2024).csv", index=False, encoding="utf-8-sig")

,C1_OBJ_NM,DT,C1,PRD_SE,UNIT_NM_ENG,ITM_ID,TBL_ID,ITM_NM,TBL_NM,PRD_DE,LST_CHN_DE,C1_NM,UNIT_NM,ORG_ID
0,시·도별,2274336,A00,A,Case,T001,DT_445001_013,헌혈실적,시·도별 인구대비 헌혈실적,2005,2018-07-02,합계,건,445
1,시·도별,2302542,A00,A,Case,T001,DT_445001_013,헌혈실적,시·도별 인구대비 헌혈실적,2006,2018-07-02,합계,건,445
2,시·도별,2087762,A00,A,Case,T001,DT_445001_013,헌혈실적,시·도별 인구대비 헌혈실적,2007,2018-07-02,합계,건,445
3,시·도별,2347184,A00,A,Case,T001,DT_445001_013,헌혈실적,시·도별 인구대비 헌혈실적,2008,2018-07-02,합계,건,445
4,시·도별,2569954,A00,A,Case,T001,DT_445001_013,헌혈실적,시·도별 인구대비 헌혈실적,2009,2018-07-02,합계,건,445

In [ ]:
# 한글컬럼변경
region = region.rename(columns={
    "C1_OBJ_NM": "시도구분",
    "DT": "값",
    "C1": "시도코드",
    "PRD_SE": "기간구분",
    "UNIT_NM_ENG": "단위(영문)",
    "ITM_ID": "항목ID",
    "TBL_ID": "테이블ID",
    "ITM_NM": "항목명",
    "TBL_NM": "테이블명",
    "PRD_DE": "기준연도",
    "LST_CHN_DE": "최종수정일",
    "C1_NM": "시도명",
    "UNIT_NM": "단위",
    "ORG_ID": "기관ID"
})

region.head()


# 필요한 컬럼만 남기기

region = region[["시도명", "기준연도", "값", "항목명",'단위']]
region.head()

print(region.columns.tolist())

['시도명', '기준연도', '값', '항목명', '단위']

In [ ]:
print(region[region['단위']=='명']['값'].head(20))

40    48138077
41    48297184
42    48456369
43    48606787
44    48746693
45    48874539
46    48988833
47    50004441
48    50219669
49    50423955
50    50617045
51    50801405
52    51446201
53    51635256
54    51849861
55    51829023
56    51638809
57    51439038
58    51325329
59    51217221
Name: 값, dtype: object

In [ ]:
region.info()

# 값 전처리 (문자 → 숫자)
region['값'] = (
    region['값']
    .astype(str)
    .str.replace(',', '')   # 쉼표 제거
    .str.strip()            # 공백 제거
)

# 2숫자 변환
region['값'] = pd.to_numeric(region['값'], errors='coerce')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 840 entries, 0 to 839
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   시도명     840 non-null    object
 1   기준연도    840 non-null    object
 2   값       840 non-null    object
 3   항목명     840 non-null    object
 4   단위      840 non-null    object
dtypes: object(5)
memory usage: 32.9+ KB

In [ ]:
#  합계 제거
region = region[region['시도명'] != '합계']

# 컬럼 삭제
# region = region.drop(columns=['항목명'])

# 단위컬럼 정리
region = region[region['단위'] != '%']

In [ ]:
# 건,명 컬럼생성
# region['값'] = region.to_numeric(df['값'], errors='coerce')

region = region.pivot_table(
    index=['시도명', '기준연도'],
    columns='단위',
    values='값',
    aggfunc='first'
).reset_index()

# 컬럼 이름 정리
region_pivot.columns.name = None

In [ ]:
print(region.columns)
region.head()

# 건,명 결측치확인
region['건'].isnull().sum()
region['명'].isnull().sum()

Index(['시도명', '기준연도', '건', '명'], dtype='object', name='단위')

np.int64(0)

In [ ]:
# 데이터확인
region.info()
# region

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   시도명     260 non-null    object
 1   기준연도    260 non-null    object
 2   건       260 non-null    float64
 3   명       260 non-null    float64
dtypes: float64(2), object(2)
memory usage: 8.3+ KB

In [ ]:
region.to_csv("region_clean.csv", index=False, encoding="utf-8-sig")

# 연령별 헌혈 통계

In [ ]:

url='https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=NDM2YzQ2NTdiNTBkM2QyNDg4ZjYyNDYzNzg4OTQwY2U=&itmId=T001+T002+&objL1=ALL&objL2=ALL&objL3=ALL&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=Y&startPrdDe=2005&endPrdDe=2024&orgId=445&tblId=DT_445001_003'
def get_data(url):
    response = requests.get(url)
    response.raise_for_status()
    
    data = response.json()
    
    if isinstance(data, dict):
        data = data.get("list", data)
    
    return pd.DataFrame(data)

age = get_data(url)
age.head()

#원본저장
age.to_csv("age(2005~2024).csv", index=False, encoding="utf-8-sig")

rename_dict = {
    "C1_OBJ_NM": "성별구분",
    "C1_OBJ_NM_ENG": "성별구분(영문)",

    "C1": "성별코드",
    "C1_NM": "성별명",
    "C1_NM_ENG": "성별명(영문)",

    "C2_OBJ_NM": "연령구분",
    "C2": "연령코드",
    "C2_NM": "연령명",

    "C3_OBJ_NM": "혈액원구분",
    "C3": "혈액원코드",
    "C3_NM": "혈액원명",

    "DT": "헌혈건수",

    "PRD_DE": "기준연도",
    "PRD_SE": "기간구분",

    "ITM_ID": "항목ID",
    "ITM_NM": "항목명",

    "TBL_ID": "테이블ID",
    "TBL_NM": "테이블명",

    "UNIT_NM": "단위",
    "UNIT_NM_ENG": "단위(영문)",

    "LST_CHN_DE": "수정일",
    "ORG_ID": "기관ID"
}

age= age.rename(columns=rename_dict)
age.head()

# age['연령명'].unique() #'합계', '16~19세', '20~29세', '30~39세', '40~49세', '50~59세', '60세이상'
age.columns

Index(['성별구분', '연령명', '혈액원코드', '헌혈건수', '연령코드', '성별코드', '기간구분', '단위(영문)',
       '항목ID', '테이블ID', '항목명', '테이블명', '기준연도', '수정일', '성별명', '단위', '혈액원명',
       '혈액원구분', '기관ID', '성별구분(영문)', '연령구분', '성별명(영문)'],
      dtype='object')

In [ ]:
age = age[[
    "연령코드",
    "연령명",
    "기준연도",
    "헌혈건수",
    '단위'
]]

# A001 제거
age = age[age["연령코드"] != "A001"]

# 코드 변환 
age_map = {
    "A002": 10,
    "A003": 20,
    "A004": 30,
    "A005": 40,
    "A006": 50,
    "A007": 60
}

age["연령코드"] = age["연령코드"].map(age_map)

# 타입 안정화
age = age.dropna(subset=['연령코드'])
age["연령코드"] = age["연령코드"].astype(int)

# 연령대 라벨 생성
age_label = {
    10: "16~19세",
    20: "20~29세",
    30: "30~39세",
    40: "40~49세",
    50: "50~59세",
    60: "60세이상"
}

age["연령대"] = age["연령코드"].map(age_label)

# 확인
# age

# 헌혈건수 분리
age['단위'].unique()

array(['건', '%'], dtype=object)

In [ ]:
age.columns

Index(['연령코드', '연령명', '기준연도', '헌혈건수', '단위', '연령대'], dtype='object')

In [ ]:
age.head()

age = age.pivot_table(
    index=["연령코드", "연령대", "기준연도",'연령명'],
    columns="단위",
    values="헌혈건수",
    aggfunc="first"
).reset_index()

age.head()

단위  연령코드     연령대  기준연도     연령명     %       건
0     10  16~19세  2005  16~19세  31.1  707262
1     10  16~19세  2006  16~19세    33  760145
2     10  16~19세  2007  16~19세  35.2  735107
3     10  16~19세  2008  16~19세  36.3  851751
4     10  16~19세  2009  16~19세  34.9  897580

In [ ]:

# 컬럼삭제
# age =age.drop(columns=['연령명','%'])
# age.info()

age['기준연도'] = age['기준연도'].astype(int)
age['건'] = age['건'].astype(int)
# 데이터저장

age.to_csv("age_clean.csv", index=False, encoding="utf-8-sig")

# 직업별 통계

In [ ]:

url='https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=NDM2YzQ2NTdiNTBkM2QyNDg4ZjYyNDYzNzg4OTQwY2U=&itmId=T001+T002+&objL1=ALL&objL2=ALL&objL3=ALL&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=Y&startPrdDe=2005&endPrdDe=2024&orgId=445&tblId=DT_445001_004'
def get_data(url):
    response = requests.get(url)
    response.raise_for_status()
    
    data = response.json()
    
    if isinstance(data, dict):
        data = data.get("list", data)
    
    return pd.DataFrame(data)

job = get_data(url)
job.head()
# job.columns

#원본저장
# job.to_csv("job(2005~2024).csv", index=False, encoding="utf-8-sig")

rename_dict = {
    "C1_OBJ_NM": "성별구분",
    "C1_OBJ_NM_ENG": "성별구분(영문)",

    "C1": "성별코드",
    "C1_NM": "성별명",
    "C1_NM_ENG": "성별명(영문)",

    "C2_OBJ_NM": "직업구분",
    "C2": "직업코드",
    "C2_NM": "직업명",

    "C3_OBJ_NM": "혈액원구분",
    "C3": "혈액원코드",
    "C3_NM": "혈액원명",

    "DT": "헌혈건수",

    "PRD_DE": "기준연도",
    "PRD_SE": "기간구분",

    "ITM_ID": "항목ID",
    "ITM_NM": "항목명",

    "TBL_ID": "테이블ID",
    "TBL_NM": "테이블명",

    "UNIT_NM": "단위",
    "UNIT_NM_ENG": "단위(영문)",

    "ORG_ID": "기관ID",
    "LST_CHN_DE": "수정일"
}

job = job.rename(columns=rename_dict)
job.head()
# job['직업명'].unique() # '고등학생', '대학생', '군인', '회사원', '공무원', '자영업', '종교직', '가사', '기타

,성별구분,직업명,혈액원코드,헌혈건수,직업코드,성별코드,기간구분,단위(영문),항목ID,테이블ID,항목명,테이블명,기준연도,수정일,성별명,단위,혈액원명,혈액원구분,기관ID,성별구분(영문),직업구분,성별명(영문)
0,성별,합계,C01,2274336,A01,0,A,Case,T001,DT_445001_004,실적,직업별 헌혈통계,2005,2018-03-23,계,건,합계,혈액원별,445,By gender,직업별,NaN
1,성별,합계,C01,2302542,A01,0,A,Case,T001,DT_445001_004,실적,직업별 헌혈통계,2006,2018-03-23,계,건,합계,혈액원별,445,By gender,직업별,NaN
2,성별,합계,C01,2087762,A01,0,A,Case,T001,DT_445001_004,실적,직업별 헌혈통계,2007,2018-03-23,계,건,합계,혈액원별,445,By gender,직업별,NaN
3,성별,합계,C01,2347184,A01,0,A,Case,T001,DT_445001_004,실적,직업별 헌혈통계,2008,2018-03-23,계,건,합계,혈액원별,445,By gender,직업별,NaN
4,성별,합계,C01,2569954,A01,0,A,Case,T001,DT_445001_004,실적,직업별 헌혈통계,2009,2018-03-23,계,건,합계,혈액원별,445,By gender,직업별,NaN

In [ ]:
# 컬럼정리
job = job[[
    "직업명",
    "직업코드",
    "기준연도",
    "헌혈건수",
    '단위'
]]



# 직업명
job['직업명'].unique()
job = job[~job['직업명'].isin(['합계','기타'])]


# job['직업코드'].unique()
# job = job[~job["혈액원명"].isin(['합계','대한적십자사 외'])]

# 합계삭제,분리

job['헌혈건수']

job = job.pivot_table(
    index=["직업명", "직업코드",'기준연도'],
    columns="단위",
    values="헌혈건수",
    aggfunc="first"
).reset_index()

# %에 0인값이많아서 삭제
job = job.drop(columns=['%'])

In [ ]:
job.head()
# 성별코드,혈액원명 삭제
# job = job.drop(columns=['성별코드','혈액원명'])
job.head()

단위 직업명 직업코드  기준연도      건
0   가사  A09  2005  20529
1   가사  A09  2006  22893
2   가사  A09  2007  20961
3   가사  A09  2008  23988
4   가사  A09  2009  27420

In [ ]:
job.tail()

단위   직업명 직업코드  기준연도       건
155  회사원  A05  2020  849493
156  회사원  A05  2021  847679
157  회사원  A05  2022  914277
158  회사원  A05  2023  956681
159  회사원  A05  2024  980370

In [ ]:
# job['건'].isnull().sum() # 건
# job['건'] = job['건'].fillna(0).astype(int)

job.head(23)
# 건 타입변경
import numpy as np
import pandas as pd

job['건'] = job['건'].replace('-', np.nan)
  
job['건'] = job['건'].astype(int)

# 데이터저장

job.to_csv("job_clean.csv", index=False, encoding="utf-8-sig")

# 장소별통계

In [ ]:
url='https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=NDM2YzQ2NTdiNTBkM2QyNDg4ZjYyNDYzNzg4OTQwY2U=&itmId=T001+T002+&objL1=ALL&objL2=ALL&objL3=ALL&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=Y&startPrdDe=2005&endPrdDe=2024&orgId=445&tblId=DT_445001_005'
def get_data(url):
    response = requests.get(url)
    response.raise_for_status()
    
    data = response.json()
    
    if isinstance(data, dict):
        data = data.get("list", data)
    
    return pd.DataFrame(data)

location = get_data(url)
location.head()

#원본저장
location.to_csv("location(2005~2024).csv", index=False, encoding="utf-8-sig")


rename_dict = {
    "C1_OBJ_NM": "성별구분",
    "C1_OBJ_NM_ENG": "성별구분(영문)",

    "C1": "성별코드",
    "C1_NM": "성별명",
    "C1_NM_ENG": "성별명(영문)",

    "C2_OBJ_NM": "장소구분",
    "C2": "장소코드",
    "C2_NM": "장소명",

    "C3_OBJ_NM": "혈액원구분",
    "C3": "혈액원코드",
    "C3_NM": "혈액원명",

    "DT": "헌혈건수",

    "PRD_DE": "기준연도",
    "PRD_SE": "기간구분",

    "ITM_ID": "항목ID",
    "ITM_NM": "항목명",

    "TBL_ID": "테이블ID",
    "TBL_NM": "테이블명",

    "UNIT_NM": "단위",
    "UNIT_NM_ENG": "단위(영문)",

    "ORG_ID": "기관ID",
    "LST_CHN_DE": "수정일"
}

location= location.rename(columns=rename_dict)
location['장소명'].unique() # 합계', '단체헌혈', '고등학교', '대학교', '군부대', '종교', '일반단체', '개인헌혈', '원내',
                            #'헌혈의집', '가두

                            #가두 : 야외·이동 장소에서 진행하는 헌혈

array(['합계', '단체헌혈', '고등학교', '대학교', '군부대', '종교', '일반단체', '개인헌혈', '원내',
       '헌혈의집', '가두'], dtype=object)

In [ ]:
# 필요한 컬럼
location = location[['장소코드', '장소명', '혈액원명','헌혈건수','단위']]
# 합계 행 삭제
location = location[location['혈액원명'] != '합계']
# 대한적십자사 외 행 확인
len([location['혈액원명'] != '대한적십자사 외']) 
# 1건 -> 삭제
location=location[location['혈액원명'] != '대한적십자사 외']
# 장소명 합계삭제
location = location[location['장소명'] != '합계']


# 장소명에 기관,유형,장소가 섞여있음 분리작업 
len(location['혈액원명']=='대한적십자사')

# 기관구분 컬럼 생성
location['기관구분'] = '지역혈액원'

location.loc[location['혈액원명'] == '대한적십자사', '기관구분'] = '중앙기관'

location.loc[location['혈액원명'] == '대한적십자사 외', '기관구분'] = '기타'
location.head(10)

    장소코드   장소명    혈액원명     헌혈건수 단위  기관구분
406  A01  단체헌혈  대한적십자사  1209466  건  중앙기관
407  A01  단체헌혈  대한적십자사  1060939  건  중앙기관
408  A01  단체헌혈  대한적십자사   899402  건  중앙기관
409  A01  단체헌혈  대한적십자사   965846  건  중앙기관
410  A01  단체헌혈  대한적십자사   923908  건  중앙기관
411  A01  단체헌혈  대한적십자사   883772  건  중앙기관
412  A01  단체헌혈  대한적십자사   827700  건  중앙기관
413  A01  단체헌혈  대한적십자사   880801  건  중앙기관
414  A01  단체헌혈  대한적십자사   922787  건  중앙기관
415  A01  단체헌혈  대한적십자사   928716  건  중앙기관

In [ ]:
location.info()


# 장소명
(location['장소명'] == '종교').sum()
# 일반헌혈 510,단체 510,개인 510

# 헌혈유형 분리하기 (추정)
location['추정헌혈유형'] = pd.Series(index=location.index, dtype='object')

location.loc[
    location['장소명'].isin(['고등학교','대학교','군부대','종교','일반단체','단체헌혈']),
    '추정헌혈유형'
] = '단체'

location.loc[
    location['장소명'].isin(['헌혈의집','가두','원내','개인헌혈']),
    '추정헌혈유형'
] = '개인'

# 장소명 유형 이름 변경

location = location[~location['장소명'].isin(['단체헌혈','개인헌혈','일반단체'])]
location.head()

<class 'pandas.core.frame.DataFrame'>
Index: 19560 entries, 406 to 23017
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   장소코드    19560 non-null  object
 1   장소명     19560 non-null  object
 2   혈액원명    19560 non-null  object
 3   헌혈건수    19560 non-null  object
 4   단위      19560 non-null  object
 5   기관구분    19560 non-null  object
dtypes: object(6)
memory usage: 1.0+ MB

       장소코드   장소명    혈액원명    헌혈건수 단위  기관구분 추정헌혈유형
1138  A0101  고등학교  대한적십자사  293838  건  중앙기관     단체
1139  A0101  고등학교  대한적십자사  321625  건  중앙기관     단체
1140  A0101  고등학교  대한적십자사  308519  건  중앙기관     단체
1141  A0101  고등학교  대한적십자사  337228  건  중앙기관     단체
1142  A0101  고등학교  대한적십자사  284924  건  중앙기관     단체

In [ ]:
# 결측치 -> nan 변경
location['헌혈건수'] = location['헌혈건수'].replace('-', np.nan)
location['헌혈건수'].isnull().sum() # 45개


# 컬럼정리
# location = location.drop(columns=['단위','기관구분'])
location.isnull().sum()
# location[['장소명','헌혈건수']]

장소코드        0
장소명         0
혈액원명        0
헌혈건수      192
추정헌혈유형      0
dtype: int64

In [ ]:
# location['단위'].unique()
location = location[location['단위'] != '%']
location.head()

       장소코드   장소명    혈액원명    헌혈건수 단위  기관구분 추정헌혈유형
1138  A0101  고등학교  대한적십자사  293838  건  중앙기관     단체
1139  A0101  고등학교  대한적십자사  321625  건  중앙기관     단체
1140  A0101  고등학교  대한적십자사  308519  건  중앙기관     단체
1141  A0101  고등학교  대한적십자사  337228  건  중앙기관     단체
1142  A0101  고등학교  대한적십자사  284924  건  중앙기관     단체

In [ ]:
# 결측치 제거
# 가두,지역혈액원,A0203 매번다른장소에서 진행되는 가두는 헌혈건수측정 xx
# 0으로 대체
location[location['헌혈건수'].isna()]
location['헌혈건수'] = location['헌혈건수'].fillna(0)
location['헌혈건수'] = location['헌혈건수'].astype(int)


location.isnull().sum()
location.info()
# 데이터저장
location.to_csv("location_clean.csv", index=False, encoding="utf-8-sig")

# location.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 6846 entries, 1138 to 22997
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   장소코드    6846 non-null   object
 1   장소명     6846 non-null   object
 2   혈액원명    6846 non-null   object
 3   헌혈건수    6846 non-null   int64
 4   추정헌혈유형  6846 non-null   object
dtypes: int64(1), object(4)
memory usage: 320.9+ KB

# 혈액형별 통계

In [ ]:
url='https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=NDM2YzQ2NTdiNTBkM2QyNDg4ZjYyNDYzNzg4OTQwY2U=&itmId=T001+T002+&objL1=ALL&objL2=ALL&objL3=ALL&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=Y&startPrdDe=2005&endPrdDe=2024&orgId=445&tblId=DT_445001_006'

def get_data(url):
    response = requests.get(url)
    response.raise_for_status()
    
    data = response.json()
    
    if isinstance(data, dict):
        data = data.get("list", data)
    
    return pd.DataFrame(data)

Bloodtype = get_data(url)
Bloodtype.head()

#원본저장
Bloodtype.to_csv("Bloodtype(2005~2024).csv", index=False, encoding="utf-8-sig")

rename_dict = {

    "C1_OBJ_NM": "성별구분",
    "C1_OBJ_NM_ENG": "성별구분(영문)",

    "C1": "성별코드",
    "C1_NM": "성별명",
    "C1_NM_ENG": "성별명(영문)",

    "C2_OBJ_NM": "혈액형구분",
    "C2": "혈액형코드",
    "C2_NM": "혈액형명",

    "C3_OBJ_NM": "혈액원구분",
    "C3": "혈액원코드",
    "C3_NM": "혈액원명",

    "DT": "헌혈건수",

    "PRD_DE": "기준연도",
    "PRD_SE": "기간구분",

    "ITM_ID": "항목ID",
    "ITM_NM": "항목명",

    "TBL_ID": "테이블ID",
    "TBL_NM": "테이블명",

    "UNIT_NM": "단위",
    "UNIT_NM_ENG": "단위(영문)",

    "ORG_ID": "기관ID",
    "LST_CHN_DE": "수정일"
}

# 컬럼명 변경
Bloodtype = Bloodtype.rename(columns=rename_dict)

In [ ]:
# 컬럼 삭제
# 필요한 컬럼만 선택
Bloodtype = Bloodtype[['헌혈건수', '혈액형명', '혈액형코드','단위']]
Bloodtype.head()

      헌혈건수 혈액형명 혈액형코드 단위
0  2274336   합계   A00  건
1  2302542   합계   A00  건
2  2087762   합계   A00  건
3  2347184   합계   A00  건
4  2569954   합계   A00  건

In [ ]:
# 혈액형명

# 혈액형명 합계삭제
# Bloodtype = Bloodtype[~(Bloodtype['혈액형명']=='합계')]
# 단위 % 삭제
Bloodtype = Bloodtype[~(Bloodtype['단위']=='%')]

# ~형 삭제
Bloodtype['혈액형명'].unique() #['O형', 'A형', 'B형', 'AB형']
Bloodtype['혈액형명'] = Bloodtype['혈액형명'].str.replace('형','',regex=False)
# 혈액형코드 A00삭제
Bloodtype = Bloodtype[~(Bloodtype['혈액형코드']=='A01')]

#수혈의 안정성때문에 분리되어있음
# RH+ 
Bloodtype['혈액형명'] = Bloodtype['혈액형코드'].str[-2:].map({
    '01': 'O',
    '02': 'A',
    '03': 'B',
    '04': 'AB'
})

Bloodtype[['혈액형코드','혈액형명']]
# RH-,+ NAN 값 제거
Bloodtype = Bloodtype[Bloodtype['혈액형코드'] != 'A00']
# Bloodtype['혈액형명'].unique()

In [ ]:
# 결측치확인
Bloodtype['헌혈건수'].isnull().sum()

np.int64(0)

In [ ]:
# 데이터확인
Bloodtype.tail()

      헌혈건수 혈액형명  혈액형코드 단위
23033   26   AB  A0204  건
23034   22   AB  A0204  건
23035   36   AB  A0204  건
23036   36   AB  A0204  건
23037   31   AB  A0204  건

In [ ]:
# 데이터 확인
# 단위 drop
Bloodtype=Bloodtype.drop(columns=['단위'])
Bloodtype.head()
# 저장
Bloodtype.to_csv("Bloodtype_clean.csv", index=False, encoding="utf-8-sig")

In [ ]:
Bloodtype.head()

        헌혈건수 혈액형명  혈액형코드 단위
1098  620195    O  A0101  건
1099  628496    O  A0101  건
1100  571421    O  A0101  건
1101  640707    O  A0101  건
1102  700095    O  A0101  건

# 년도별 헌혈자 통계

In [ ]:
import requests
import pandas as pd

url = "https://kosis.kr/openapi/statisticsData.do?method=getMeta&apiKey=NDM2YzQ2NTdiNTBkM2QyNDg4ZjYyNDYzNzg4OTQwY2U=&format=json&type=TBL&orgId=445&tblId=DT_445001_007&jsonVD=Y"

params = {
    "method": "getList",
    "apiKey": "YOUR_KEY",
    "itmId": "T001+T002+T003+T004+T005+T006+T007+T008",
    "objL1": "A05",   # ← 핵심 (예: 시도/직업/혈액형 등)
    "format": "json",
    "jsonVD": "Y",
    "prdSe": "Y",
    "startPrdDe": "2005",
    "endPrdDe": "2024",
    "orgId": "445",
    "tblId": "DT_445001_007"
}

def get_data(url, params):
    res = requests.get(url, params=params)

    # 1. 상태 체크
    if res.status_code != 200:
        print("HTTP ERROR:", res.status_code)
        print(res.text)
        return pd.DataFrame()

    # 2. JSON 변환 안전 처리
    try:
        data = res.json()
    except Exception:
        print("JSON 아님 → 응답 내용:")
        print(res.text)
        return pd.DataFrame()

    # 3. API 구조 체크
    if isinstance(data, dict) and "list" in data:
        return pd.DataFrame(data["list"])

    return pd.DataFrame(data)

df = get_data(url, params)
df.head()

if "err" in data:
    print("API 오류:", data)
    return pd.DataFrame()

return pd.DataFrame(data.get("list", []))


df = get_data(url, params)

df.head()
df.to_csv("year.csv", index=False, encoding="utf-8-sig")

HTTP ERROR: 404



<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>KOSIS 공유서비스</title>
	<link rel="stylesheet" href="/openapi/css/error.css">

	<script src="/openapi/js/jquery-3.7.0.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function(){
			setTimeout(function() {
				location.href="/openapi/index.jsp";
			}, 5000);
		});
	</script>
</head>

<body>

	<div class="error_wrap">
		<div class="center">
			<h1 class="logo">
				<a href="/openapi/index.jsp"><img src="/openapi/image/error/logo.png" alt="KOSIS공유서비스" /></a>
			</h1>
			<h2 class="title">국가통계포털 <span class="text_blue2">사이트 변경안내</span></h2>
			<div class="error_box">
				<p>국가통계포털 서비스를 이용하여 주셔서 감사합니다.</p>
				<p><span class="text_blue">국가통계포털 서비스 개편에 따라</span> <br>
					요청하신 페이지가 <span class="text_red">새로운 주소로 변경되었으니</span><br>
					설정된 북마크를 수정하여 주시기 바랍니다.
				</p>
			</div>
			<div class="btn_box">
				<a href="/openapi/index.jsp" class="btn btn_home">메인으로 돌아가기</a>
			</div>
		</div>
	</div>

</body>
</html>

SyntaxError: 'return' outside function (2435111542.py, line 48)

In [74]:
year.head()
# year.columns

#'시점', '총 헌혈실적 (건)', '총 인구 (명)', '헌혈률 (%)', '헌혈가능인구 (16~69세) (명)',
    #    '헌혈가능인구대비 헌혈률 (%)', '헌혈자 실인원 (명)', '헌혈자 1인당 평균 헌혈실적 (건)',
    #    '실제 국민 헌혈률 (%)'

,시점,총 헌혈실적 (건),총 인구 (명),헌혈률 (%),헌혈가능인구 (16~69세) (명),헌혈가능인구대비 헌혈률 (%),헌혈자 실인원 (명),헌혈자 1인당 평균 헌혈실적 (건),실제 국민 헌혈률 (%)
0,2005,2274336,48138077,4.72,33895487,6.71,1544784,1.47,4.56
1,2006,2302542,48371946,4.76,34127502,6.75,1508229,1.53,4.42
2,2007,2087762,48597652,4.30,34356556,6.08,1421906,1.47,4.14
3,2008,2347184,48948698,4.80,34708544,6.76,1526914,1.54,4.40
4,2009,2569954,49182038,5.23,34995947,7.34,1596809,1.61,4.56

In [ ]:
rename_dict = {
    "C1_OBJ_NM": "지역구분",

    "C1": "지역코드",
    "C1_NM": "지역명",

    "DT": "값",

    "PRD_DE": "기준연도",
    "PRD_SE": "주기",

    "ITM_ID": "지표ID",
    "ITM_NM": "지표명",

    "TBL_ID": "테이블ID",
    "TBL_NM": "테이블명",

    "UNIT_NM": "단위",
    "UNIT_NM_ENG": "단위(영문)",

    "ORG_ID": "기관ID",
    "LST_CHN_DE": "수정일"
}

year= year.rename(columns=rename_dict)

In [ ]:
# 필요한 컬럼
year=year[['기준연도','값','단위','지역명']]

# 단위 분리
# % 제거
year = year[year['단위'] != '%'].copy()

year['값'] = pd.to_numeric(year['값'], errors='coerce')

#  pivot (건, 명 만들기)
pivot_df = year.pivot_table(
    index=['기준연도','지역명'],
    columns='단위',
    values='값'
).reset_index()

# #  원본에 붙이기
# result = year.merge(pivot_df, on=['기준연도','지역명'], how='left')

#  단위 컬럼 제거 + 컬럼 정리
years = pivot_df[['기준연도', '건', '명','지역명']]
# 합계 삭제
years = years[years['지역명']!='합계']
years.head()
years.info()

# 기준연도 타입변경
years['기준연도']=years['기준연도'].astype(int)
years['건']=years['건'].astype(int)
years['명']=years['명'].astype(int)



# 저장
years.to_csv("years_data.csv", index=False, encoding="utf-8-sig")

<class 'pandas.core.frame.DataFrame'>
Index: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   기준연도    13 non-null     object
 1   건       13 non-null     float64
 2   명       13 non-null     float64
 3   지역명     13 non-null     object
dtypes: float64(2), object(2)
memory usage: 520.0+ bytes

# 헌혈방법별 헌혈통계

In [ ]:
url='https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=NDM2YzQ2NTdiNTBkM2QyNDg4ZjYyNDYzNzg4OTQwY2U=&itmId=T001+T002+&objL1=ALL&objL2=ALL&objL3=ALL&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=Y&startPrdDe=2005&endPrdDe=2024&orgId=445&tblId=DT_445001_001'

def get_data(url):
    response = requests.get(url)
    response.raise_for_status()
    
    data = response.json()
    
    if isinstance(data, dict):
        data = data.get("list", data)
    
    return pd.DataFrame(data)

                               

method = get_data(url)
method.head()

# 원본저장
method.to_csv("method(2005~2024).csv", index=False, encoding="utf-8-sig")    

rename_dict = {
    "C1_OBJ_NM": "성별구분",
    "C1_OBJ_NM_ENG": "성별구분(영문)",

    "C1": "성별코드",
    "C1_NM": "성별명",
    "C1_NM_ENG": "성별명(영문)",

    "C2_OBJ_NM": "헌혈방법구분",
    "C2": "헌혈방법코드",
    "C2_NM": "헌혈방법명",

    "C3_OBJ_NM": "혈액원구분",
    "C3": "혈액원코드",
    "C3_NM": "혈액원명",

    "DT": "헌혈건수",

    "PRD_DE": "기준연도",
    "PRD_SE": "기간구분",

    "ITM_ID": "항목ID",
    "ITM_NM": "항목명",

    "TBL_ID": "테이블ID",
    "TBL_NM": "테이블명",

    "UNIT_NM": "단위",
    "UNIT_NM_ENG": "단위(영문)",

    "ORG_ID": "기관ID",
    "LST_CHN_DE": "수정일"
}

method = method.rename(columns=rename_dict)
method['헌혈방법명'].unique() #'합계', '전혈헌혈', '320mL', '400mL', '성분헌혈', '혈장', '혈소판', '다종성분', '기타

array(['합계', '전혈헌혈', '320mL', '400mL', '성분헌혈', '혈장', '혈소판', '다종성분', '기타'],
      dtype=object)

In [ ]:
method.head()
method.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16656 entries, 0 to 16655
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   성별구분      16656 non-null  object
 1   헌혈방법명     16656 non-null  object
 2   혈액원코드     16656 non-null  object
 3   헌혈건수      16656 non-null  object
 4   헌혈방법코드    16656 non-null  object
 5   성별코드      16656 non-null  object
 6   기간구분      16656 non-null  object
 7   단위(영문)    16656 non-null  object
 8   항목ID      16656 non-null  object
 9   테이블ID     16656 non-null  object
 10  항목명       16656 non-null  object
 11  테이블명      16656 non-null  object
 12  기준연도      16656 non-null  object
 13  수정일       16656 non-null  object
 14  성별명       16656 non-null  object
 15  단위        16656 non-null  object
 16  혈액원명      16656 non-null  object
 17  혈액원구분     16656 non-null  object
 18  기관ID      16656 non-null  object
 19  성별구분(영문)  16656 non-null  object
 20  헌혈방법구분    16656 non-null  object
 21  성별명(영문)   11081 non-null  object
dtypes: object(22)
memory usage: 2.8+ MB

In [ ]:
method =method[['헌혈방법명', '헌혈건수', '헌혈방법코드', '단위']]
method['헌혈방법명'].unique() # 삭제 = 합계,기타,'320mL', '400mL' 
method = method[~method['헌혈방법명'].isin(['합계', '기타', '320ml', '400ml'])]

method['헌혈건수'].unique()

method['헌혈방법코드'].unique() 
#A01', 'A0101', 'A0102', 'A02', 'A0201', 'A0202', 'A0203
method = method[~method['헌혈방법명'].isin(['합계', '기타', '320mL', '400mL'])]
 # % 삭제
method = method[method['단위'] != '%']

method['헌혈방법명'].unique()  #전혈헌혈', '성분헌혈', '혈장', '혈소판', '다종성분'
# method[['헌혈방법명','헌혈방법코드']]

# 단위 삭제
method=method.drop(columns=['단위'])
# 저장
method.to_csv("method_clean.csv", index=False, encoding="utf-8-sig")

## 헌혈방법 두가지 
> 전혈,성분헌혈

| 값        | 의미                  |
| -----    | ------------------- |
| 합계      | 전체 합산               |
| 전혈헌혈  | Whole Blood (전체 혈액) |
| 320mL    | 전혈헌혈 (320ml 기준)     |
| 400mL    | 전혈헌혈 (400ml 기준)     |
| 성분헌혈  | Apheresis (성분헌혈 전체) |
| 혈장      | Plasma donation     |
| 혈소판    | Platelet donation   |
| 다종성분  | 복합 성분헌혈             |
| 기타      | 기타 헌혈방법             |

# 수혈용 혈액 보유 추이

In [ ]:
url ='https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=NDM2YzQ2NTdiNTBkM2QyNDg4ZjYyNDYzNzg4OTQwY2U=&itmId=T001+&objL1=ALL&objL2=&objL3=&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=Y&startPrdDe=2005&endPrdDe=2024&orgId=445&tblId=DT_445001_011'

def get_data(url):
    response = requests.get(url)
    response.raise_for_status()
    
    data = response.json()
    
    if isinstance(data, dict):
        data = data.get("list", data)
    
    return pd.DataFrame(data)


stock = get_data(url)
stock.head()

# 원본저장
stock.to_csv("stock(2005~2024).csv", index=False, encoding="utf-8-sig")    
                            


rename_dict = {
    "C1_OBJ_NM": "구분",

    "C1": "일자코드",
    "C1_NM": "일자",

    "DT": "혈액보유량",

    "PRD_SE": "주기",
    "PRD_DE": "기준연도",

    "ITM_ID": "항목ID",
    "ITM_NM": "항목명",

    "TBL_ID": "테이블ID",
    "TBL_NM": "테이블명",

    "UNIT_NM": "단위",
    "UNIT_NM_ENG": "단위(영문)",

    "ORG_ID": "기관ID",
    "LST_CHN_DE": "수정일"
}

stock = stock.rename(columns=rename_dict)
# 최소 혈액보유량 일자 찾기
stock['혈액보유량']


# 월별데이터로변경

stock['혈액보유량'] = pd.to_numeric(stock['혈액보유량'], errors='coerce')
stock['월'] = stock['일자'].str[:2]

# monthly = stock.groupby("월")["혈액보유량"].mean().reset_index()

In [ ]:
stock.columns
# 구분', '혈액보유량', '일자코드', '주기', '단위(영문)', '항목ID', '테이블ID', '항목명', '테이블명',
    #    '기준연도', '수정일', '일자', '단위', '기관ID', '월'
# 컬럼 삭제
stock=stock[['혈액보유량','월']]
stock=stock.sort_values(by='월',ascending=True)

stock['월'] = stock['월'].astype(int)

stock.info()

# 원본저장
stock.to_csv("stock_clean.csv", index=False, encoding="utf-8-sig")

<class 'pandas.core.frame.DataFrame'>
Index: 7308 entries, 0 to 5744
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   혈액보유량   7306 non-null   float64
 1   월       7308 non-null   int64
dtypes: float64(1), int64(1)
memory usage: 171.3 KB

- data 월별헌혈건수
- total 총헌혈수(지역별)
- age 연령대별
- job 직업별 
- location 위치별
- Bloodtype 혈액형별
- year_per (년도별 헌혈자 통계)
- method 헌혈방법별 (성분,전혈)
- stock 혈액재고(일별)

> 원본데이터 저장

In [1]:
import pandas as pd
import os

base = r"c:\AI project\전처리"

files = [
    "age_clean.csv",
    "Bloodtype_clean.csv",
    "job_clean.csv",
    "location_clean.csv",
    "method_clean.csv",
    "month_clean.csv",
    "region_clean.csv",
    "stock_clean.csv",
    'year_clean.csv'
]

BD = {}

for file in files:
    path = os.path.join(base, file)
    
    print("loading:", path)
    
    df = pd.read_csv(path)
    
    df = df.rename(columns={'건': '헌혈건수'})
    
    BD[file] = df





age= BD["age_clean.csv"]
Bloodtype= BD["Bloodtype_clean.csv"]
job= BD["job_clean.csv"]
location= BD["location_clean.csv"]
method= BD["method_clean.csv"]
month= BD["month_clean.csv"]
region= BD["region_clean.csv"]
stock= BD["stock_clean.csv"]
year= BD['year_clean.csv']

loading: c:\AI project\전처리\age_clean.csv
loading: c:\AI project\전처리\Bloodtype_clean.csv
loading: c:\AI project\전처리\job_clean.csv
loading: c:\AI project\전처리\location_clean.csv
loading: c:\AI project\전처리\method_clean.csv
loading: c:\AI project\전처리\month_clean.csv
loading: c:\AI project\전처리\region_clean.csv
loading: c:\AI project\전처리\stock_clean.csv
loading: c:\AI project\전처리\year_clean.csv

In [64]:
# # =========================================
# # 데이터 타입 변경,라벨 인코딩
# # =========================================
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# ========================================
# age
# =======================================
# age= 연령대삭제
# age = age.drop(columns=['연령대'])


# ========================================
# job
# =======================================

# job = 직업명 인코딩(int),직업코드삭제

# job = job.drop(columns=['직업코드'])


le = LabelEncoder()
job["직업명"] = le.fit_transform(job["직업명"])
job.info()

# ========================================
# location
# =======================================

# location = 장소코드삭제,장소명(인코딩),추정헌혈유형(삭제),혈액원명 삭제

location=location[['장소명','헌혈건수']]

location['장소명'] = le.fit_transform(location['장소명'])
location.info()


# ========================================
# region
# =======================================
# region =시도명(인코딩)
region['시도명']= le.fit_transform(region['시도명'])

# ========================================
# method
# =======================================
# method=헌혈방법코드 삭제 ,헌혈방법명 인코딩,헌혈건수 int
# method = method.drop(columns=['헌혈방법코드'])
method['헌혈방법명'] = le.fit_transform(method['헌혈방법명'])
# method = method.drop(columns=['헌혈방법코드'])
method.info()

# ========================================
# bloodtype
# =======================================
# bloodtype = 혈액형명인코딩,혈액형코드삭제,헌혈건수int
# Bloodtype['헐액형명'] = le.fit_transform(Bloodtype['혈액형명'])
# Bloodtype = Bloodtype.drop(columns=['혈액형코드'])
# Bloodtype['헌혈건수']=Bloodtype['헌혈건수'].astype(int)

Bloodtype[Bloodtype['헌혈건수']=='-']

# #9723	-	AB	1
# #9725	-	AB	1

import numpy as np


Bloodtype["헌혈건수"] = Bloodtype["헌혈건수"].replace("-", np.nan)
Bloodtype["헌혈건수"] = pd.to_numeric(Bloodtype["헌혈건수"])

Bloodtype.isnull().sum() # 결측치 2개

# 결측치 ab형 평균건수로 대체
# ab_mean = Bloodtype[Bloodtype["혈액형명"] == "AB"]["헌혈건수"].mean()

# Bloodtype.loc[
#     (Bloodtype["혈액형명"] == "AB") &
#     (Bloodtype["헌혈건수"].isnull()),
#     "헌혈건수"
# ] = ab_mean

# Bloodtype.isnull().sum() 
# Bloodtype.head()

Bloodtype=Bloodtype.drop(columns=['혈액형코드'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   직업명     160 non-null    int64
 1   기준연도    160 non-null    int64
 2   헌혈건수    160 non-null    int64
dtypes: int64(3)
memory usage: 3.9 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6846 entries, 0 to 6845
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   장소명     6846 non-null   int64
 1   헌혈건수    6846 non-null   int64
dtypes: int64(2)
memory usage: 107.1 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5045 entries, 0 to 5044
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   헌혈방법명   5045 non-null   int64
 1   헌혈건수    5045 non-null   object
dtypes: int64(1), object(1)
memory usage: 79.0+ KB

In [69]:
BD2 = {
    "age": age,
    "job": job,
    "location": location,
    "region": region,
    "method": method,
    "Bloodtype": Bloodtype,
    "stock": stock
}


import os

# 저장 폴더 생성
os.makedirs('전처리2', exist_ok=True)

# 데이터 저장
for name, df in BD2.items():
    
    save_path = f'전처리2/{name}2.csv'
    
    df.to_csv(save_path,
              index=False,
              encoding='utf-8-sig')
    
    print(f'{save_path} 저장 완료')

전처리2/age2.csv 저장 완료
전처리2/job2.csv 저장 완료
전처리2/location2.csv 저장 완료
전처리2/region2.csv 저장 완료
전처리2/method2.csv 저장 완료
전처리2/Bloodtype2.csv 저장 완료
전처리2/stock2.csv 저장 완료